export const ENV = {
  appUrl: process.env.APP_URL ?? process.env.VITE_APP_URL ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  supabaseUrl: process.env.SUPABASE_URL ?? "",
  supabasePublishableKey: process.env.SUPABASE_PUBLISHABLE_KEY ?? "",
  supabaseServiceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY ?? "",
  supabaseStorageBucket: process.env.SUPABASE_STORAGE_BUCKET ?? "uploads",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  geminiApiKey: process.env.GEMINI_API_KEY ?? "",
  geminiModel: process.env.GEMINI_MODEL ?? "gemini-2.5-flash",
  googleMapsApiKey: process.env.GOOGLE_MAPS_API_KEY ?? "",
  googlePagespeedApiKey: process.env.GOOGLE_PAGESPEED_API_KEY ?? "",
  googleCustomSearchApiKey: process.env.GOOGLE_CUSTOM_SEARCH_API_KEY ?? "",
  googleCustomSearchEngineId: process.env.GOOGLE_CUSTOM_SEARCH_ENGINE_ID ?? "",
  s3AccessKeyId: process.env.S3_ACCESS_KEY_ID ?? "",
  s3SecretAccessKey: process.env.S3_SECRET_ACCESS_KEY ?? "",
  s3Bucket: process.env.S3_BUCKET ?? "",
  s3Region: process.env.S3_REGION ?? "",
  s3Endpoint: process.env.S3_ENDPOINT ?? "",
  publicStorageBaseUrl: process.env.PUBLIC_STORAGE_BASE_URL ?? "",
  // Bright Data
  brightDataWsEndpoint: process.env.BRIGHT_DATA_WS_ENDPOINT ?? "",
  brightDataApiToken: process.env.BRIGHT_DATA_API_TOKEN ?? "",
  brightDataSerpHost: process.env.BRIGHT_DATA_SERP_HOST ?? "brd.superproxy.io",
  brightDataSerpPort: parseInt(process.env.BRIGHT_DATA_SERP_PORT ?? "33335"),
  brightDataSerpUsername: process.env.BRIGHT_DATA_SERP_USERNAME ?? "",
  brightDataSerpPassword: process.env.BRIGHT_DATA_SERP_PASSWORD ?? "",
  brightDataSerpZone: process.env.BRIGHT_DATA_SERP_ZONE ?? "serp_api1",
};
